SELECT * FROM RMTYPE_PRICE
SELECT * From ARRANGE where OBNO=19554
SELECT * FROM ORDERS_D where ODID=000715
SELECT * FROM ORDERS where ODNAME='ด๚ธี'

SELECT * From ARRANGE where OBNO=19554
SELECT * FROM arrange WHERE ARPRICE=2592

SELECT * FROM RMTYPE_PRICE
SELECT * From ARRANGE 
SELECT * FROM ORDERS_D 
SELECT * FROM ORDERS
SELECT * FROM ROOM 

select * from xpara